djmarketplace/app_cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

djmarketplace/app_orders/urls.py
from django.urls import path

from . import views


app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('order/<int:order_id>', views.order_page, name='order_page'),
    path('history/', views.OrdersHistory.as_view(), name='orders_history'),
]

djmarketplace/djmarketplace/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('i18n', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', include('app_users.urls')),
    path('cart/', include('app_cart.urls', namespace='cart')),
    path('', include('app_shops.urls', namespace='shop')),
    path('orders/', include('app_orders.urls', namespace='orders')),
]

djmarketplace/app_cart/models.py
from django.db import models

# Create your models here.

djmarketplace/app_cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label=_('Количество'))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

djmarketplace/app_cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from app_shops.models import Product
from .cart import Cart
from .forms import CartAddProductForm


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'],
                     'update': True})
    return render(request, 'app_cart/cart_page.html', {'cart': cart})


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect(product.get_absolute_url())


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

djmarketplace/app_cart/templates/app_cart/cart_page.html
<!DOCTYPE html>
{% extends "base_template.html" %}
{% load i18n %}

<html lang="ru">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>{% trans 'Корзина' %}</title>
    {% endblock %}

</head>
<body>
    {% block content %}
    <h1>{% trans 'Корзина' %}</h1>
    <table>
        <thead>
            <tr>
                <th>{% trans 'Изображение' %}</th>
                <th>{% trans 'Товар' %}</th>
                <th>{% trans 'Количество' %}</th>
                <th>{% trans 'Удалить' %}</th>
                <th>{% trans 'Цена за 1 шт' %}</th>
                <th>{% trans 'Цена' %}</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <td>
                    <img src="{{ MEDIA_URL }}{{ product.product_photo }}" width="200" height="200">
                </td>
                <td>
                    <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                </td>
                <td>
                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                    {% csrf_token %}
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.update }}
                    <input type="submit" value="{% trans 'Изменить' %}">
                    </form>
                </td>
                <td><a href="{% url 'cart:cart_remove' product.id%}">{% trans 'Удалить' %}</a></td>
                <td>{{ item.price }} {% trans 'руб' %}</td>
                <td>{{ item.total_price }} {% trans 'руб' %}</td>
            </tr>
            {% endwith %}
            {% endfor %}
            <tr>
                <td>{% trans 'Итого' %}</td>
                <td colspan="4"></td>
                <td>{{ cart.get_total_price }} {% trans 'руб' %}</td>
            </tr>
        </tbody>
    </table>
    <button><a href="{% url 'orders:order_create' %}">{% trans 'Оформить заказ' %}</a></button>
    {% endblock %}
</body>
</html>