djmarketplace/app_cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

djmarketplace/app_orders/urls.py
from django.urls import path

from . import views


app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('order/<int:order_id>', views.order_page, name='order_page'),
    path('history/', views.OrdersHistory.as_view(), name='orders_history'),
]

djmarketplace/app_users/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('login', BuyerLoginView.as_view(), name='login'),
    path('logout', BuyerLogoutView.as_view(), name='logout'),
    path('register', register_view, name='register'),
    path('account', account_view, name='account'),
    path('top_up_balance', top_up_balance_view, name='top_up_balance'),
    path('about_statuses', about_statuses_view, name='about_statuses'),
]

djmarketplace/djmarketplace/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('i18n', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', include('app_users.urls')),
    path('cart/', include('app_cart.urls', namespace='cart')),
    path('', include('app_shops.urls', namespace='shop')),
    path('orders/', include('app_orders.urls', namespace='orders')),
]

djmarketplace/app_users/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _

from app_shops.models import Offers


class Profile(models.Model):
    STATUS_CHOICES = (
        ('b', _('Базовый')),
        ('s', _('Серебряный')),
        ('g', _('Золотой')),
        ('p', _('Платиновый'))
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True, verbose_name=_('дата рождения'))
    city = models.CharField(max_length=50, verbose_name=_('город'))
    balance = models.DecimalField(default=0, max_digits=10, decimal_places=2, verbose_name=_('баланс'))
    offers = models.ManyToManyField(Offers, blank=True, verbose_name=_('предложения'),
                                    related_name='usr_offer')
    status_balance = models.DecimalField(default=0, max_digits=10, decimal_places=2, verbose_name=_('сумма покупок'))
    status_name = models.CharField(max_length=1, default='b', choices=STATUS_CHOICES, verbose_name=_('статус'))

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = _('профили')
        verbose_name = _('профиль')

djmarketplace/app_users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms.widgets import NumberInput
from django.utils.translation import gettext_lazy as _


class RegisterForm(UserCreationForm):
    date_of_birth = forms.DateField(label=_('Дата рождения'), widget=NumberInput(attrs={'type': 'date'}))
    city = forms.CharField(max_length=50, label=_('Город'))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'date_of_birth', 'city', 'email', 'password1', 'password2')


class BalanceForm(forms.Form):
    money = forms.DecimalField(label=_('Пополнить баланс'))

djmarketplace/app_users/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.core.cache import cache
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

from .models import Profile
from .forms import RegisterForm, BalanceForm
from .utils import check_for_info_user_status, change_user_status
import app_shops.utils as utils
from app_orders.models import Order, OrderItem


@login_required
def account_view(request):
    product_promo_cache_key = f'product_promotions:{request.user.username}'
    shop_promo_cache_key = f'shop_promotions:{request.user.username}'
    offer_cache_key = f'offers:{request.user.username}'

    profile = Profile.objects.select_related('user').get(user=request.user)
    product_promotions = utils.get_product_promo_for_account(5)
    shop_promotions = utils.get_shop_promo_for_account(3)
    exclusive_promo = utils.get_exclusive_promo_for_account(3)
    offers = profile.offers.all()

    user_account_cache_data = {
        product_promo_cache_key: product_promotions,
        shop_promo_cache_key: shop_promotions,
        offer_cache_key: offers
    }
    cache.set_many(user_account_cache_data)

    change_user_status(profile.id)

    context = {
        'profile': profile,
        'shop_items': utils.get_shop_item_from_promo(shop_promotions),
        'product_items': utils.get_product_item_from_promo(product_promotions),
        'exclusive_promo': exclusive_promo,
        'offers': offers,
        'about_status': check_for_info_user_status(profile)
    }

    orders = Order.objects.prefetch_related('user').filter(user=request.user.profile.id)
    if orders:
        unpaid_orders = Order.objects.prefetch_related('user').filter(paid=False)
        if unpaid_orders:
            context['unpaid_orders'] = unpaid_orders
        else:
            last_order = Order.objects.prefetch_related('user').first()
            context['last_order'] = OrderItem.objects.prefetch_related('order').filter(order=last_order.id)
    else:
        context['orders_count'] = 0

    return render(request, 'app_users/account.html', context=context)


class BuyerLoginView(LoginView):
    template_name = 'app_users/login.html'


class BuyerLogoutView(LogoutView):
    template_name = 'app_users/logout.html'


def register_view(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            city = form.cleaned_data.get('city')
            date_of_birth = form.cleaned_data.get('date_of_birth')
            Profile.objects.create(user=user, city=city, date_of_birth=date_of_birth)
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('/account')
        else:
            return redirect('/')
    else:
        form = RegisterForm()
    return render(request, 'app_users/register.html', {'form': form})


@login_required
def top_up_balance_view(request):
    if request.method == 'POST':
        form = BalanceForm(request.POST)
        if form.is_valid():
            user = Profile.objects.get(user=request.user)
            user.balance += form.cleaned_data.get('money')
            user.save()
            return HttpResponseRedirect('account')
    else:
        form = BalanceForm()

    return render(request, 'app_users/balance.html', {'form': form})


def about_statuses_view(request):
    return render(request, 'app_users/about_statuses.html')

djmarketplace/app_users/templates/app_users/about_statuses.html
<!DOCTYPE html>
{% extends "base_template.html" %}
{% load i18n %}

<html lang="ru">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>{% trans 'Статусы' %}</title>
    {% endblock %}

</head>
<body>
    {% block content %}
    <h1>{% trans 'Статусная система для пользователей маркетплейса' %}</h1>
    <h2>{% trans 'Чем больше покупаете, тем выгоднее становятся ваши покупки!' %}</h2>
    <p>{% trans 'Помимо акций, которые предлагают магазины на свои товары, наша платформа предоставляет пользователям возможность получить выгоду от покупок. Каждый пользователь автоматически подключается к системе лояльности. В ней предусмотрено четыре статуса.' %}</p>
    <h3>{% trans 'Базовый статус' %}</h3>
    <p>{% trans 'При регистрации пользователь имеет данный статус. Необходимо приобрести товары на сумму 10000р, чтобы получить следующий статус.' %}</p>
    <h3>{% trans 'Серебряный статус' %}</h3>
    <p>{% trans 'Накопление средств для перехода на следующий статус становится быстрее, так как к сумме покупки прибавляется 5% от стоимости заказа. Например, если пользователь приобрёл фен за 3350р, то в системе лояльности будет засчитана сумма 3517,5р. Также пользователю становятся доступны выгодные персональные предложения, которые можно увидеть в личном кабинете.' %}</p>
    <h3>{% trans 'Золотой статус' %}</h3>
    <p>{% trans 'Пользователь получает данный статус, когда сумма его покупок достигла 100000р. Теперь на все покупки, с учетом акций, добавляется скидка 3%. Тот же самый фен, на который сегодня скидка 15% от магазина, пользователь приобретёт со скидкой 18%, т.е. за 2747р. Система лояльности засчитывает сумму покупки без учета скидки в 3%.' %}</p>
    <h3>{% trans 'Платиновый статус' %}</h3>
    <p>{% trans 'Пользователь получает данный статус, когда сумма его покупок достигла 500000р. Это самый высокий статус. Пользователю доступна скидка 5% на все товары, а также открывается доступ к эксклюзивным акциям.' %}</p>

    {% endblock %}

</body>
</html>

djmarketplace/app_users/templates/app_users/account.html
<!DOCTYPE html>
{% extends "base_template.html" %}
{% load i18n %}
{% load cache %}

<html lang="ru">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>{% trans 'Личный кабинет' %}</title>
    {% endblock %}
</head>
<body>
    {% block content %}
    <h1>{% trans 'Личный кабинет' %}</h1>

    <h2>{% trans 'Личная информация' %}</h2>
    <p>{% trans 'Имя' %}: {{ request.user.first_name }}</p>
    <p>{% trans 'Фамилия' %}: {{ request.user.last_name }}</p>
    <p>{% trans 'Дата рождения' %}: {{ profile.date_of_birth }}</p>
    <p>{% trans 'Эл. почта' %}: {{ request.user.email }}</p>
    <p>{% trans 'Город' %}: {{ profile.city }}</p>
    <p>{% trans 'Баланс' %}: {{ profile.balance }}.
        <a href="{% url 'top_up_balance' %}">{% trans 'Пополнить баланс' %}</a>
    </p>
    <p>{% trans 'Статус' %}: {{ profile.get_status_name_display }}</p>
    <p>{{ about_status }}</p>
    <a href="{% url 'about_statuses' %}">{% trans 'Подробнее о статусной программе' %}</a>


    {% block history_list %}
        <h2>{% trans 'Ваши заказы' %}</h2>
        {% if not orders_count %}
            {% if unpaid_orders %}
                <h3>{% trans 'Ожидается оплата' %}:</h3>
                {% for order in unpaid_orders %}
                    <p>{% trans 'Номер заказа' %}: {{ order.id }}</p>
                    {% for item in order.items.all %}
                        <p>{% trans 'Товар' %}
                            <a href="{{ item.product.get_absolute_url }}">{{ item.product }}</a>,
                            {{ item.quantity }} {% trans 'шт за' %} {{ item.price }} {% trans 'руб' %}.</p>
                    {% endfor %}
                    <p><a href="{{ order.get_absolute_url }}">{% trans 'Перейти на страницу заказа' %}</a></p>
                {% endfor %}
            {% endif %}

            {% if last_order %}
                <h3>{% trans 'Ваш последний оплаченный заказ' %}</h3>
                    {% for item in last_order %}
                        <p>{% trans 'Товар' %}
                            <a href="{{ item.product.get_absolute_url }}">{{ item.product }}</a>,
                            {{ item.quantity }} {% trans 'шт за' %} {{ item.price }} {% trans 'руб' %}.</p>
                    {% endfor %}
            {% endif %}

            <span><a href="{% url 'orders:orders_history' %}">{% trans 'Смотреть историю заказов' %}</a></span>

        {% else %}
            <p>{% trans 'У вас пока нет заказов' %}</p>
        {% endif %}

    {% endblock %}


    <h3>{% trans 'Спешите воспользоваться акциями' %}</h3>

    {% for promo, product in product_items.items %}
    <ul>
        <li>
            <p>{% trans 'Акция на товар' %}:
                <a href="{{ product.get_absolute_url }}"> {{ product }}</a>
            </p>
            {% if promo.picture %}
            <img src="{{ MEDIA_URL }}{{ promo.picture }}" width="100" height="100" style="display: block"/>
            {% endif %}
            <p>{{ promo.description }}</p>
        </li>
    </ul>
    {% endfor %}

    {% for promo, shop in shop_items.items %}
    <ul>
        <li>
            <p>{% trans 'Акция от магазина' %}
                <a href="{{ shop.get_absolute_url }}"> {{ shop }}</a>
            </p>
            {% if promo.picture %}
            <img src="{{ MEDIA_URL }}{{ promo.picture }}" width="100" height="100" style="display: block"/>
            {% endif %}
            <p>{{ promo.description }}</p>
        </li>
    </ul>
    {% endfor %}

    {% cache 3600 special %}
        {% block special_list %}

        {% if profile.status_name != 'b' %}
            <h3>{% trans 'Специальные предложения для Вас' %}</h3>

            {% for offer in offers %}
            <ul>
                <li>
                    <h4>{{ offer.description }}</h4>
                    {% if offer.picture %}
                    <img src="{{ MEDIA_URL }}{{ offer.picture }}" width="100" height="100" style="display: block"/>
                    {% endif %}
                </li>
            </ul>
            {% endfor %}

            {% if profile.status_name == 'p' %}
                {% if exclusive_promo %}
                    <h3>{% trans 'Эксклюзивные акции' %}</h3>

                    {% for ex_promo in exclusive_promo %}
                    <ul>
                        <li>
                            {% if ex_promo.picture %}
                            <img src="{{ MEDIA_URL }}{{ ex_promo.picture }}" width="100" height="100" style="display: block"/>
                            {% endif %}

                            <p>{{ ex_promo.description }}</p>

                            {% if ex_promo.shop %}
                            <p><a href="shop/{{ ex_promo.shop.id }}">{% trans 'Перейти' %}</a></p>
                            {% elif ex_promo.product %}
                            <p><a href="product/{{ ex_promo.product.id }}">{% trans 'Перейти' %}</a></p>
                            {% endif %}
                        </li>
                    </ul>}
                    {% endfor %}

                {% endif %}
            {% endif %}

        {% endif %}
        {% endblock %}
    {% endcache %}

    {% endblock %}

</body>
</html>

djmarketplace/app_users/templates/app_users/balance.html
<!DOCTYPE html>
{% extends "base_template.html" %}
{% load i18n %}
<html lang="ru">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>{% trans 'Пополнить баланс' %}</title>
    {% endblock %}
</head>
<body>
    {% block content %}
    <h2>{% trans 'Пополнить баланс' %}</h2>
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans 'Пополнить' %}</button>
    </form>
    {% endblock %}
</body>
</html>

djmarketplace/app_users/templates/app_users/login.html
<!DOCTYPE html>
{% extends "base_template.html" %}
{% load i18n %}
<html lang="ru">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>{% trans 'Логин' %}</title>
    {% endblock %}
</head>
<body>
    {% block content %}
    <h2>{% trans 'Вход в систему' %}</h2>
    <form method="post" action="">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">{% trans 'Войти' %}</button>
    </form>
    {% endblock %}
</body>
</html>

djmarketplace/app_users/templates/app_users/logout.html
<!DOCTYPE html>
{% extends "base_template.html" %}
{% load i18n %}
<html lang="ru">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>{% trans 'Выйти' %}</title>
    {% endblock %}
</head>
<body>
    {% block content %}
    <h3>{% trans 'Вы успешно вышли из своего профиля' %}</h3>
    <br>
    <a href="/">{% trans 'Вернуться на главную страницу' %}</a>
    {% endblock %}
</body>
</html>

djmarketplace/app_users/templates/app_users/register.html
<!DOCTYPE html>
{% extends "base_template.html" %}
{% load i18n %}
<html lang="ru">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>{% trans 'Регистрация' %}</title>
    {% endblock %}
</head>
<body>
    {% block content %}
    <h2>{% trans 'Регистрация' %}</h2>
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans 'Зарегистрироваться' %}</button>
    </form>
    {% endblock %}
</body>
</html>