djmarketplace/app_cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

djmarketplace/app_shops/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import main_page_view, shop_page_view, detail_product_view, ProductListView, report_view

app_name = 'shop'

urlpatterns = [
    path('', main_page_view),
    path('shop/<slug:shop_slug>', shop_page_view, name='shop'),
    path('shop/<int:shop_id>/product/<int:prod_id>', detail_product_view, name='product'),
    path('products/', ProductListView.as_view(), name='products_list'),
    path('report_best_sellers', report_view, name='report_bsp')
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djmarketplace/djmarketplace/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('i18n', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', include('app_users.urls')),
    path('cart/', include('app_cart.urls', namespace='cart')),
    path('', include('app_shops.urls', namespace='shop')),
    path('orders/', include('app_orders.urls', namespace='orders')),
]

djmarketplace/app_shops/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.core.validators import MaxValueValidator


class StoreHouse(models.Model):
    address = models.CharField(max_length=200, verbose_name=_('адрес'))
    products = models.ManyToManyField('Product', verbose_name=_('товары'), blank=True)

    def __str__(self):
        return self.address

    class Meta:
        verbose_name_plural = _('склады')
        verbose_name = _('склад')


class Shop(models.Model):
    name = models.CharField(max_length=50, verbose_name=_('название'))
    logo = models.ImageField(upload_to='logo/', blank=True, null=True, verbose_name=_('логотип'),
                             default='default/logo-default.png')
    store_house = models.OneToOneField(StoreHouse, on_delete=models.SET_NULL, null=True, blank=True,
                                       verbose_name=_('склад'))
    slug = models.SlugField(max_length=50, verbose_name=_('имя url'), unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:shop', kwargs={'shop_slug': self.slug})

    class Meta:
        verbose_name_plural = _('магазины')
        verbose_name = _('магазин')


class Product(models.Model):
    name = models.CharField(max_length=50, verbose_name=_('товар'))
    article = models.CharField(max_length=10, verbose_name=_('артикул'))
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name=_('цена'))
    description = models.TextField(blank=True, null=True, verbose_name=_('описание'))
    shop = models.ForeignKey('Shop', on_delete=models.CASCADE, verbose_name=_('магазин'))
    quantity = models.PositiveIntegerField(default=0, verbose_name='остаток на складе')
    product_photo = models.ImageField(upload_to='products/', blank=True, null=True, verbose_name=_('фото товара'),
                                      default='default/product-default.png')

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('shop:product', kwargs={'prod_id': self.pk, 'shop_id': self.shop.id})

    class Meta:
        verbose_name_plural = _('товары')
        verbose_name = _('товар')
        ordering = ['price']


class Promotions(models.Model):
    name = models.CharField(max_length=50, verbose_name=_('название акции'))
    description = models.TextField(blank=True, null=True, verbose_name=_('описание'))
    picture = models.ImageField(upload_to='promo/', blank=True, null=True, verbose_name=_('рисунок'))
    shop = models.ManyToManyField(Shop, blank=True, verbose_name=_('магазин'))
    product = models.ManyToManyField(Product, blank=True, verbose_name=_('товар'), related_name='product')
    discount_size = models.PositiveIntegerField(validators=[MaxValueValidator(100)], blank=True, null=True,
                                                verbose_name=_('размер скидки'))
    exclusive = models.BooleanField(default=False, verbose_name=_('эксклюзивная'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = _('акции')
        verbose_name = _('акция')


class Offers(models.Model):
    description = models.TextField(blank=True, null=True, verbose_name=_('описание'))
    picture = models.ImageField(upload_to='promo/', blank=True, null=True, verbose_name=_('рисунок'))

    def __str__(self):
        return self.description

    class Meta:
        verbose_name_plural = _('предложения')
        verbose_name = _('предложение')

djmarketplace/app_shops/forms.py
from django import forms
from django.forms import NumberInput
from django.utils.translation import gettext_lazy as _


class ReportForm(forms.Form):
    date_from = forms.DateTimeField(label=_('c'), widget=NumberInput(attrs={'type': 'date'}))
    date_to = forms.DateTimeField(label=_('до'), widget=NumberInput(attrs={'type': 'date'}))

djmarketplace/app_shops/views.py
# from django.core import paginator
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import ListView

from app_cart.forms import CartAddProductForm
from app_orders.models import Order
from .models import Shop, Product, Promotions
from .utils import get_product_on_market_dict, get_best_selling_products
from .forms import ReportForm


def main_page_view(request):
    object_list = Shop.objects.all()
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        shops = paginator.page(page)
    except PageNotAnInteger:
        shops = paginator.page(1)
    except EmptyPage:
        shops = paginator.page(paginator.num_pages)
    return render(request, 'index.html', {'page': page, 'shops': shops})


class ProductListView(ListView):
    model = Product
    template_name = 'product_list.html'
    paginate_by = 5

    def get_context_data(self, *args, products_list=None, **kwargs):
        products_list = Product.objects.select_related('shop').all()
        prod_in_market = get_product_on_market_dict(products_list)
        paginator = Paginator(products_list, self.paginate_by)
        context = super().get_context_data(*args, **kwargs)

        page = self.request.GET.get('page')
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)
        context['product_list'] = products
        context['product_dict'] = prod_in_market
        return context


def shop_page_view(request, shop_slug):
    shop = Shop.objects.get(slug=shop_slug)
    product_list = Product.objects.filter(shop=shop.id)
    return render(request, 'shop_detail.html', context={'shop': shop, 'product_list': product_list})


def detail_product_view(request, shop_id, prod_id):
    product = Product.objects.select_related('shop').get(id=prod_id)

    cart_product_form = CartAddProductForm()
    promo = Promotions.objects.filter(product=product.id)
    context = {
        'product': product,
        'promotions': promo,
        'cart_product_form': cart_product_form
    }
    return render(request, 'product_detail.html', context=context)


def report_view(request):
    context = {'form': ReportForm()}

    if request.method == 'POST':
        form = ReportForm(request.POST)
        if form.is_valid():
            date_from = form.cleaned_data['date_from']
            date_to = form.cleaned_data['date_to']
            orders = Order.objects.prefetch_related('user').filter(paid=True, created__gte=date_from,
                                                                   created__lte=date_to)
            if orders:
                bs_products = get_best_selling_products(orders)
                context['products'] = bs_products
                context['date_from'] = date_from
                context['date_to'] = date_to
            else:
                context['no_data'] = True

    return render(request, 'report_best_sellers.html', context=context)

djmarketplace/app_shops/templates/base_template.html
<!DOCTYPE html>
{% load i18n %}

<html lang="ru">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>Basic</title>
    {% endblock %}
</head>
<body style="background: #F5F5DC">
    {% block header %}
    <header>
        <a href="/">{% trans 'Главная' %}</a>
        <a href="/products">{% trans 'Товары' %}</a>


        {% if request.user.is_authenticated %}
            <a href="{% url 'account' %}">{% trans 'Личный кабинет' %}</a>
            <a href="{% url 'logout' %}">{% trans 'Выйти' %}</a>
        {% else %}
            <a href="{% url 'login' %}">{% trans 'Войти' %}</a>
            <a href="{% url 'register' %}">{% trans 'Регистрация' %}</a>
        {% endif %}

        {% block purchase %}
        <div>
        {% if request.user.is_authenticated %}
            <p>{% trans 'Ваш баланс' %}: {{ request.user.profile.balance }} р </p>
        {% endif %}
        </div>
        <div>
            {% with total_items=cart|length %}
            {% if cart|length > 0 %}
                {% trans 'Корзина' %}:
                <a href="{% url 'cart:cart_detail' %}">
                    {{ total_items }} {% trans 'товара на' %} {{ cart.get_total_price }} {% trans 'руб' %}.
                </a>
            {% else %}
                {% trans 'Ваша корзина пуста' %}
            {% endif %}
            {% endwith %}
        </div>
        {% endblock %}


        <form action="{% url 'set_language' %}" method="post" style="display: inline-block; float: right">
            {% csrf_token %}
            <input name="next" type="hidden" value="{{ redirect_to }}">
            <select name="language">
                {% get_current_language as LANGUAGE_CODE %}
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}

                {% for language in languages %}
                    <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
                        {{ language.name_local }} ({{ language.code }})
                    </option>
                {% endfor %}
            </select>
            <input type="submit" value="{% trans 'Выбрать' %}">
        </form>
    </header>
    {% endblock %}


    {% block content %}
    {% endblock %}
</body>
</html>

djmarketplace/app_shops/templates/index.html
<!DOCTYPE html>
{% extends "base_template.html" %}
{% load i18n %}

<html lang="ru">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>{% trans 'Главная' %}</title>
    {% endblock %}
</head>
<body>
    {% block content %}
    <h1>{% trans 'Широкий выбор магазинов - большие возможности для покупателя!' %}</h1>

    {% for shop in shops %}
        <ul>
            <li>
                <h3>{% trans 'Магазин' %} {{ shop.name }}</h3>
                <img src="{{ MEDIA_URL }}{{ shop.logo }}" width="100" height="100" style="display: block"/>
                <a href="shop/{{ shop.slug }}">{% trans 'Посмотреть ассортимент' %}</a>
            </li>
        </ul>
    {% endfor %}

    <div class="pagination">
        <span class="step-links">
            {% if shops.has_previous %}
                <a href="?page=1">&laquo; {% trans 'первая' %}</a>
                <a href="?page={{ shop_list.previous_page_number }}">{% trans 'предыдущая' %}</a>
            {% endif %}

            <span class="current">
                {% trans 'страница' %} {{ shops.number }} {% trans 'из' %} {{ shops.paginator.num_pages }}
            </span>

            {% if shops.has_next %}
                <a href="?page={{ shops.next_page_number }}">{% trans 'следующая' %}</a>
                <a href="?page={{ shops.paginator.num_pages }}">{% trans 'последняя' %} &raquo;</a>
            {% endif %}
        </span>
    </div>

    {% endblock %}

</body>
</html>

djmarketplace/app_shops/templates/product_detail.html
<!DOCTYPE html>
{% extends "base_template.html" %}
{% load i18n %}

<html lang="ru">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>{{ product.name }}</title>
    {% endblock %}
</head>
<body>

    {% block content %}
    <h1>{{ product.name }}</h1>

    {% if product.product_photo %}
        <img src="{{ MEDIA_URL }}{{ product.product_photo }}" width="20%" height="20%" style="display: block"/>
    {% endif %}
    <h3>{% trans 'Цена' %}: {{ product.price }} {% trans 'руб' %}.</h3>
    <p>{% trans 'Артикул' %} {{ product.article }}</p>

    <h3>{% trans 'Описание' %}</h3>
    <p>{{ product.description }}</p>

    <h3>{% trans 'Магазин' %}</h3>
    <p><a href="{{ product.shop.get_absolute_url }}"> {{ product.shop }}</a></p>

    {% if promotions %}
        <h3>{% trans 'Акции' %}!</h3>
        {% for p in promotions %}
            <h4>{{ p }}</h4>
            <p>{{ p.description }}</p>
            {% if p.discount_size %}
                <p>{% trans 'Скидка' %} {{ p.discount_size }}% !</p>
            {% endif %}
        {% endfor %}
    {% endif %}
    <form action="{% url 'cart:cart_add' product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <button type="submit">{% trans 'В корзину' %}</button>
    </form>

    {% endblock %}

</body>
</html>

djmarketplace/app_shops/templates/product_list.html
<!DOCTYPE html>
{% extends "base_template.html" %}
{% load i18n %}

<html lang="ru">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>{% trans 'Товары' %}</title>
    {% endblock %}
</head>
<body>
    {% block content %}
    <p><a href="{% url 'shop:report_bsp' %}">{% trans 'Узнать о самых продаваемых товарах' %}</a></p>
    <h1>{% trans 'Здесь вы найдёте товары на любой вкус' %}</h1>

    {% for product in product_list %}
        <ul>
            <li>
                <h3>{{ product }}</h3>
                <p>{% trans 'Этот товар можно приборести в магазинах' %}:</p>

                {% for prod, shops in product_dict.items %}
                    {% if prod == product.name %}
                        {% for shop in shops %}
                            <a href="{{ shop.get_absolute_url }}" >{{ shop.name }}</a>
                        {% endfor %}
                    {% endif %}
                {% endfor %}
            </li>
        </ul>
    {% endfor %}

    <div class="pagination">
        <span class="step-links">
            {% if product_list.has_previous %}
                <a href="?page=1">&laquo; {% trans 'первая' %}</a>
                <a href="?page={{ product_list.previous_page_number }}">{% trans 'предыдущая' %}</a>
            {% endif %}

            <span class="current">
                {% trans 'страница' %} {{ product_list.number }} из {{ product_list.paginator.num_pages }}.
            </span>

            {% if product_list.has_next %}
                <a href="?page={{ product_list.next_page_number }}">{% trans 'следующая' %}</a>
                <a href="?page={{ product_list.paginator.num_pages }}">{% trans 'последняя' %} &raquo;</a>
            {% endif %}
        </span>
    </div>

    {% endblock %}

</body>
</html>

djmarketplace/app_shops/templates/report_best_sellers.html
<!DOCTYPE html>
{% extends "base_template.html" %}
{% load i18n %}
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>{% trans 'Отчёт' %}</title>
    {% endblock %}

</head>
<body>
    {% block content %}
    <h2>{% trans 'Получить список самых продаваемых товаров в период' %}:</h2>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans 'Получить данные' %}</button>
    </form>
    {% if products %}
        <h3>{% trans 'Самые продаваемые товары с' %} {{ date_from }} {% trans 'по' %} {{ date_to }}</h3>
        <table>
            <tr>
                <th>id {% trans 'товара' %}</th>
                <th>{% trans 'Название' %}</th>
                <th>{% trans 'Количество' %}</th>
            </tr>
            {% for product, quantity in products.items %}
            <tr>
                <td>{{ product.id}}</td>
                <td>{{ product.name }}</td>
                <td>{{ quantity }}</td>
            </tr>
            {% endfor %}
        </table>
    {% endif %}
    {% if no_data %}
        <p>{% trans 'Нет данных по текущему запросу' %}</p>
    {% endif %}

    {% endblock %}

</body>
</html>

djmarketplace/app_shops/templates/shop_detail.html
<!DOCTYPE html>
{% extends "base_template.html" %}
{% load i18n %}

<html lang="ru">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>{{ shop.name }}</title>
    {% endblock %}

</head>
<body>
    {% block content %}
        <h1>{% trans 'Магазин' %} {{ shop.name }}</h1>
        <h2>{% trans 'Товары' %}</h2>
        <ul>
        {% for product in product_list %}
            <li>
                {% if product.product_photo %}
                <img src="{{ MEDIA_URL }}{{ product.product_photo }}" width="100" height="100" style="display: block"/>
                {% endif %}
                <p><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></p>
                <p>{{ product.price}}</p>
            </li>
        {% endfor %}
        </ul>
    {% endblock %}

</body>
</html>